### ISSUE TITLE
Combination

### ISSUE THREAD

**Issue by mdulin2** [secgroup/ctforge#1]
Man, finding a CTF platform for attack/defense has been very difficult! I was very excited to find this! However, I am looking to host a CTF with both attack/defense and jeopardy style. Does this have the capability to do a combination? If not, how hard would it be to edit the existing codebase for this? 

Thanks!

**Comment by wert310** [comment]
Yes, you simply change the `active` option in the config file to `yes` in both `mode_attackdefense` and `mode_jeopardy`. The only thing left to do, apart from setting up the network and VMs for the A/D CTF, is to change the templates to reflect you rules/setup.
Note that the two scoreboard are separated since the scoring is based on very different rules.

Also, to get the most up to date version of the platform, look at the `cyberchallenge-ad` branch.

**Comment by mdulin2** [comment]
Awesome, thank you for that!

**Comment by mdulin2** [comment]
Okay, awesome. I was really worried about that. 

The cyberchallenge-ad is not finished yet, as some of the admin functionality has some strange side effects. But, after using the version within master to the cyberchallenge-ad version I do love the added changes.
