### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by mdulin2** [secgroup/ctforge#2]
Having an major issue with flask.ext does not exist upon running the intial ctforge command. Any idea how to fix this?

**Comment by wert310** [comment]
Hi! We are unfortunately aware if this problem: the package Flask-Cache did not update when there was a global change in the naming scheme for flask extensions (https://github.com/thadeusb/flask-cache/issues/193). We are considering moving away from Flask-Cache since they seem not to maintain it anymore, but in the meantime, there is a simple fix to make it work:
Change at line `33` of the file `lib/python3.6/site-packages/Flask_Cache-0.13.1-py3.6.egg/flask_cache/jinja2ext.py` (relative to the root of your venv) the import line from
```py
from flask.ext.cache import make_template_fragment_key
```
to
```py
from flask_cache import make_template_fragment_key
```
and it should work as expected.

**Comment by mdulin2** [comment]
Yep, this fixed the issue! Thank you!
